baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cici Log'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"   # auto, dark, light
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true